version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: taskmanager_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nodetest_db
      MYSQL_USER: taskmanager
      MYSQL_PASSWORD: taskmanager123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskmanager_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # MySQL Admin (optional - remove in production)
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: taskmanager_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - taskmanager_network

volumes:
  mysql_data:
    driver: local

networks:
  taskmanager_network:
    driver: bridge
